apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    app: calculator
spec:
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 25%
  #     maxSurge: 0
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: titoo/calculator:caching
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "512Mi"
            cpu: "512m"
        readinessProbe:
          httpGet:
            path: /sum?a=1&b=2
            port: 8080