---
- hosts: web1
  become: yes
  become_method: sudo
  vars_files:
    - sudo_password.yml
  tasks:
    - name: copy configuration
      copy:
        src: foo.conf
        dest: /etc/foo.conf
      notify:
        - restart apache
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted